---
swagger: "2.0"
info:
  description: This is Currency Convert API.
  version: 1.0.0
  title: Currency Convert API
  contact:
    email: conversionco@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /konstantinklir/CurrencyConverterAPI/1.0.0
tags:
- name: Developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /CurrencyConverterAPI/CurrencyConversionService/api/authentication/:
    get:
      tags:
      - Developers
      summary: Generates JWT Token
      description: |
        By passing the api license key, the controller will issue a JWT token with an expiration date.
      operationId: authToken
      produces:
      - application/json
      parameters:
      - name: licenseKey
        in: query
        description: Pass the api license key.
        required: true
        type: string
      responses:
        "200":
          description: Valid license key and JWT token was generated.
          schema:
            type: array
            items:
              $ref: '#/definitions/Client'
        "500":
          description: Bad input parameter.
  /CurrencyConverterAPI/CurrencyConversionService/api/convert/:
    post:
      tags:
      - Developers
      summary: Converts provided amount of money
      description: |
        A POST request is made to the API, passing the correct parameters in order to compute a currency conversion.
      operationId: conversionOp
      produces:
      - application/json
      parameters:
      - name: licenseKey
        in: query
        description: Pass the api license key.
        required: true
        type: string
      - name: originalCurrency
        in: query
        description: Pass the original currency.
        required: true
        type: string
      - name: originalAmount
        in: query
        description: Pass the amount of money in the original currency.
        required: true
        type: string
      - name: convertedCurrency
        in: query
        description: Pass the converted currency type.
        required: true
        type: string
      responses:
        "201":
          description: Conversion successful and conversion files successfully created.
          schema:
            type: array
            items:
              $ref: '#/definitions/Conversion'
        "401":
          description: Unauthorized user or missing headers.
definitions:
  Client:
    type: object
    required:
    - clientID
    - clientName
    - licenseEndDate
    - licenseKey
    - licenseNumber
    - licenseStartDate
    properties:
      clientID:
        type: integer
        example: 1
      clientName:
        type: string
        example: TechInc
      licenseNumber:
        type: string
        format: uuid
        example: ABC123
      licenseStartDate:
        type: string
        format: date
        example: 2020-07-30T00:00:00.000+0000
      licenseEndDate:
        type: string
        format: date
        example: 2021-09-30T00:00:00.000+0000
      licenseKey:
        type: string
        format: uuid
        example: KEYABC123
  Conversion:
    required:
    - clientID
    - completionDate
    - conversionID
    - convertedAmount
    - convertedCurrency
    - originalAmount
    - originalCurrency
    - requestDate
    properties:
      conversionID:
        type: integer
        example: 15
      clientID:
        type: integer
        example: 1
      requestDate:
        type: string
        example: 2021-07-28T00:00:00.000+0000
      completionDate:
        type: string
        example: 2021-09-28T00:00:00.000+0000
      originalCurrency:
        type: string
        example: USD
      convertedCurrency:
        type: string
        example: CAD
      originalAmount:
        type: number
        example: 15.23
      convertedAmount:
        type: number
        example: 18.44
